kebandaweb/kebanda/urls.py
from django.urls import path
from . import views


app_name = "kebanda"
urlpatterns = [
    # ex: /polls/
    path("", views.landingPage, name="landingPage"),
    path("signup/", views.signup, name="signupPage"),
    path("login/", views.login, name="loginPage"),
    path("profile/", views.profile, name="profilePage"),
    path("logout/", views.logout, name="logout"),
    path("myshop/", views.myshop, name="myshop"),
    path("myduka/", views.myduka, name="myduka"),
    path('add_item/', views.add_item, name='add_item'),
    path('vendor-registration/', views.vendor_registration, name='vendor_registration'),
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
         ]


kebandaweb/kebandaweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("kebanda/", include("kebanda.urls", "user_administration.urls")),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kebandaweb/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

kebandaweb/kebanda/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image=models.ImageField(default='default.jpg', upload_to='profile_images')

    def __str__(self):
        return f'username: {self.user.username}'

kebandaweb/kebanda/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from stores.models import Item, Shop, Vendor

from django.forms.widgets import PasswordInput, TextInput

#create user form
class CreateUserForm(UserCreationForm):
    class Meta:
        model= User
        fields=['username','email','password1','password2']

#user authentication login form

class LoginForm(AuthenticationForm):
    username= forms.CharField(widget=TextInput())
    password= forms.CharField(widget=PasswordInput())


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'stock_quantity', 'image']

class VendorRegistrationForm(forms.ModelForm):
    bio = forms.CharField(max_length=500, required=False)

    class Meta:
        model = Vendor
        fields = ['bio']

class ShopCreationForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'description', 'location', 'profile_image']


kebandaweb/kebanda/views.py
from django.shortcuts import render,redirect, get_object_or_404, Http404
from .forms import CreateUserForm, LoginForm, ItemForm, VendorRegistrationForm, ShopCreationForm
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from . models import Profile
from stores.models import Item, Shop, Vendor
from django.contrib.auth.forms import AuthenticationForm


def landingPage(request):
    items=Item.objects.all()
    context= {'items': items}
    return render( request, "kebanda/index.html", context=context)

def signup(request):
    form=CreateUserForm()
    if request.method == 'POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            user_profile=Profile(user=user)
            user_profile.save()
            return redirect("/kebanda/login/")
        
    context={'signupform':form}
    return render(request,"kebanda/signup.html",context= context)

def login(request):
    form= LoginForm()

    if request.method =='POST':
        form =LoginForm(request, data=request.POST)

        if form.is_valid():

            username=request.POST.get('username')
            password=request.POST.get('password')

            user = authenticate(request, username=username, password= password)

            if user is not None:
                auth.login(request, user)
                context={'username':username}
            
                return redirect('/kebanda/profile/')
            
    context={'loginform':form}
    return render(request, "Kebanda/login.html",context=context)

@login_required(login_url='/kebanda/login/')
def profile(request):
    user= request.user
    try:
        person = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        raise Http404("No Profile matches the given query.")
    context={'user': user, 'person': person}
    return render(request, 'kebanda/profile.html', context= context)


@login_required(login_url='/kebanda/login/')
def logout(request):
    auth.logout(request)
    return redirect('/kebanda/login/')

@login_required(login_url='/kebanda/login/')
def myshop(request):
    if request.user.is_authenticated:
        # Retrieve the related shop for the current user
        try:
            user_shop = request.user.vendor.shop
            user_items=Item.objects.filter(shop__vendor__user=request.user)
        except Shop.DoesNotExist:
            user_shop = None
        
        return render(request, 'kebanda/myshopsprofile.html', {'user_shop': user_shop,
                                                               'user_items': user_items})
    else:
        # Redirect or handle the case when the user is not authenticated
        return redirect('login') 
    

@login_required(login_url='/kebanda/login/')
def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            # Set the shop field to the user's shop
            form.instance.shop = request.user.vendor.shop
            form.save()
            return redirect('/kebanda/myshop/')  # Redirect to a success page or the item list
    else:
        form = ItemForm()

    return render(request, 'kebanda/additem.html', {'form': form})


@login_required
def vendor_registration(request):
    user = request.user  # Get the current logged-in user

    if request.method == 'POST':
        vendor_form = VendorRegistrationForm(request.POST)
        auth_form = AuthenticationForm(request, data=request.POST)
        shop_form = ShopCreationForm(request.POST, request.FILES)

        if vendor_form.is_valid() and auth_form.is_valid() and shop_form.is_valid():
            # Authenticate user with provided password
            authenticated_user = auth_form.get_user()

            if authenticated_user == user:
                # Create a vendor associated with the user
                vendor = Vendor.objects.create(user=user, bio=vendor_form.cleaned_data['bio'])

                # Create a shop associated with the vendor
                shop = shop_form.save(commit=False)
                shop.vendor = vendor
                shop.save()

                return redirect('/kebanda/myshop/')  # Redirect to a success page
    else:
        vendor_form = VendorRegistrationForm()
        auth_form = AuthenticationForm()
        shop_form = ShopCreationForm()

    return render(request, 'kebanda/vendor_registration.html', {'vendor_form': vendor_form, 'auth_form': auth_form, 'shop_form': shop_form})


@login_required
def edit_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)

    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            # Redirect to the item detail page or the shop's dashboard
            return redirect('/kebanda/myshop/')  # Update with your actual dashboard URL
    else:
        form = ItemForm(instance=item)
    return render(request, 'kebanda/edititem.html', {'form': form, 'item': item})

@login_required
def myduka(request):
    if request.user.is_authenticated:
        # Retrieve the related shop for the current user
        try:
            user_items=Item.objects.filter(shop__vendor__user=request.user)
        except Shop.DoesNotExist:
            user_shop = None
        
        return render(request, 'kebanda/myduka.html', {'user_items': user_items})
    else:
        # Redirect or handle the case when the user is not authenticated
        return redirect('login') 

kebandaweb/kebanda/templates/kebanda/additem.html
{% extends 'kebanda/index.html' %}
{% block title %}login - Kebanda{% endblock %}


{% block content %}
    <h2 style="color: orange;">Add New Item</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add Item</button>
    </form>
{% endblock %}

kebandaweb/kebanda/templates/kebanda/edititem.html
{% extends 'kebanda/index.html' %}
{% block title %}edit-item{% endblock %}

{% block content %}
  <h1>Edit Item: {{ item.name }}</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form}}
    <button type="submit">Save changes</button>
  </form>
  
  <a href="{% url 'kebanda:myshop' %}">Back to MyShop</a>  <!-- Update with your actual dashboard URL -->
{% endblock %}

kebandaweb/kebanda/templates/kebanda/index.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">

  {% block head %}
    <head> 
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <title>{% block title %}Kebanda Home {% endblock%}</title>    
      <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

      <link rel="stylesheet" href="{% static 'kebanda/style.css' %}">
      <link rel="stylesheet" href="{% static 'kebanda/formstyle.css' %}">
      
    </head>
  {% endblock %}
  <body> 
    <header>
      
      <div class="topnav">
        <img src="{% static 'kebanda/images/kebanda_logo.png' %}" style="float: left;">
        <a class="active" href="{% url 'kebanda:landingPage'%}">Home</a>
        <a href="#">News</a>
        <a href="#">Help</a>
        <a href="#">Q&A</a>
    {% if user.is_authenticated %}


    
        <a href="{% url 'kebanda:profilePage' %}">MyProfile</a>
        {% if user.vendor %}
        <a href="{% url 'kebanda:myshop' %}">MyShop</a>
        {% else %}
        <a href="{% url 'kebanda:vendor_registration'%}" style="background-color: orangered; color: white;">Vend</a>
        {% endif %}
        <a href="{% url 'kebanda:logout' %}">Logout</a>
        

    {% else %}
        <a href="{% url 'kebanda:signupPage'%}">Sign-Up</a>
        <a href="{% url 'kebanda:loginPage'%}">Login</a>

    {% endif %}
        
    
      </div>

    </header>
    {% if messages %}
        {% for message in messages %}
            <div> {{ message }} </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    <div class="searchform">
      <div>
        <form>
          <input type="search" placeholder="Search" aria-label="Search">
          <button type="submit">Search</button>
        </form>
        <h1 style="color: orange;">Welcome to Kebanda</h1> 
      </div>
    </div>
    <a href="{% url 'kebanda:vendor_registration'%}"><card>sell on kebanda now</card></a>
    

    <div class="home_box">     
      <p> Kebanda is an open e-market where you can sell or buy handmade items or show your services to potential customers.
        Join other kebandans on a journer of transforming trade. Create a Vendors account and exhibit your products and services</p>

    </div>
<!--
    <div>
      <h2 style="color: orange;">Available Now</h2>
      <div class="container">
        <div class="row">
          {% for item in items %}
          <div class="col-sm container">
            <div>
                <img src="{{ item.image.url }}" alt="Item Image" class="img-fluid" style="max-width: 200px; height: 200px;"> 
                <p style="color: orange;">{{ item.name }}</p>
                <p style="background-color: orange;">
                    <label><small>Ksh</small> {{ item.price }} </label>
                    <a href="#">Add to Cart</a>
                </p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  -->
    

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <footer style="border-top: solid orange; margin-top: 15%;">
      <div class="bg-dark">
        <p>&copy; <strong> KeBanda</strong>. All rights reserved.</p>
        <p>Designed<span style="color: #28a745;"> by</span>  Deni&co</p>
      </div>
    </footer>
  </body>
</html>

kebandaweb/kebanda/templates/kebanda/login.html

{% extends 'kebanda/index.html' %}
{% block title %}login - Kebanda{% endblock %}


{% block content %}
    <h1 style="color: orange;">Login</h1>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
            {{loginform}}
        <input type="submit" name="login">
        
    </form>
{% endblock %}

kebandaweb/kebanda/templates/kebanda/myduka.html
{% extends 'kebanda/index.html' %}
{% load static %}
{% block title %}MyShop-Inventory{% endblock %}

{% block content %}
<div>
    <h1>MyDuka Inventory Manager</h1>
</div>
<div>
    <div style="text-align: left;">
        <ul>
            {% for item in user_items %}
            <li style="color: white; padding: 3px; border: solid; border-color: orange; border-radius: 2px; border-width: 1px; margin-right: 5px;" >
                <div>
                    <img src="{{ item.image.url }}" alt="Item Image" class="img-fluid" style="max-width: 50px; height: 50px;"> 
                     {{ item.name }} <a href="{% url 'kebanda:edit_item' item.id %}">update</a>
                     {{ item.description }} <label><small>Ksh</small> {{ item.price }}</label>
                    <strong> in stock : {{ item.stock_quantity }}</strong>
                </div>
            </li>
            {% endfor %}

        </ul>

    </div>
</div>
{% endblock %}

kebandaweb/kebanda/templates/kebanda/myshopsprofile.html
{% extends 'kebanda/index.html' %}
{% load static %}
{% block title %}MyShop- Kebanda{% endblock %}

{% block content %}

    <div>
        <div>
            <div>
                {% if user_shop %}
                    <div style="background-image: url('{{ user_shop.profile_image.url }}'); background-size: contain; margin: 5%; border-radius: 5px;">
                        <div style="background-color: rgba(0, 0, 0, 0.637);">
                            <h1><p style="color: orange;">{{ user_shop.name }}</p></h1>
                            <img src="{{ user_shop.profile_image.url }}" alt="shop profile photo" class="img-fluid" style="max-width: 200px; height: 200px; float:initial;">
                        </div>
                        <div style="background-color: orange;">
                            <small><strong>{{user_shop.location}}</strong></small>
                            <h2 style="color: white; padding: 20px;">{{ user_shop.description }}</h2>
                        </div>
                        <div class="topnav" style="background-color: green;">
                            <a href="{% url 'kebanda:add_item' %}">Add Item</a>
                            <a href="#">update Shop Profile</a>
                            <a href="{% url 'kebanda:myduka' %}">MyDuka Inventory & Stock Manager </a>
                            <a href="#"></a>
                            <a href="#" style="float: right;">Close Shop</a>
                        </div>
                    </div>
                    <div class="row" style="margin: 5%;">
                    {% for item in user_items %}
                    
                        <div class="col-sm container">
                            <div>
                                <img src="{{ item.image.url }}" alt="Item Image" class="img-fluid" style="max-width: 200px; height: 200px;"> 
                                <p style="color: orange;">{{ item.name }} <a href="{% url 'kebanda:edit_item' item.id %}">update</a></p>
                                <p style="overflow: hidden;"> - {{ item.description }}</p> 
                                <p style="background-color: orange;"><label><small>Ksh</small> {{ item.price }}</label></p>
                                <p><strong> in stock : {{ item.stock_quantity }}</strong></p>
                            </div>
                        
                        </div>
                    {% endfor %}
                    </div>

                {% else %}
                    <p>You don't have a shop yet. <a href="{% url 'create_shop' %}">Create a Shop</a></p>
                {% endif %}
            </div>
        </div>            
    </div>
    
    
    
{% endblock %}

kebandaweb/kebanda/templates/kebanda/profile.html
{% extends 'kebanda/index.html' %}
{% load static %}
{% block title %}profile - Kebanda{% endblock %}

{% block content %}

    <div class="container">
        
        <div >
            <h1 >My Profile</h1>
            <div style="background-color: white; margin: 5%; border-radius: 5px;">
                
                {% if person %}
                    <!-- Display profile-specific information -->
                    <p><img src="{{ person.profile_image.url }}" alt="Profile Image" class="img-fluid" style="max-width: 300px; height: auto;"></p>
                    <!-- Add more profile-specific information as needed -->
                    <div>
                        <h2>User Information</h2>
                        <small><a href="#">update user info</a></small>
                        <h3><strong>Username:</strong> {{ user.username }}</h3>
                        <h4><strong>Email:</strong> {{ user.email }}</h4>                
                    </div>
                {% else %}
                    <p class="card-text">No profile information found for this user.</p>
                {% endif %}
            </div>
        </div>            
    </div>
    
    
    
{% endblock %}

kebandaweb/kebanda/templates/kebanda/signup.html

{% extends 'kebanda/index.html' %}
{% block title %}signup - Kebanda{% endblock %}


{% block content %}
    <h1 style="color: orange;">Signup</h1>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
            {{signupform}}
        <input type="submit" name="signup">
        
    </form>
{% endblock %}

kebandaweb/kebanda/templates/kebanda/test.html
To achieve the layout you described, you can use CSS to style the form and header elements. Here's an example of how you can modify your code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      margin: 0;
    }

    div {
      display: flex;
      flex-direction: column;
      align-items: center;
      background-color: black;
    }

    form {
      display: flex;
      width: 100%;
      justify-content: center;
      padding: 10px; /* Add padding for better visual appearance */
    }

    input {
      width: 80%;
      padding: 8px;
    }

    button {
      width: 20%;
      padding: 8px;
      margin-left: 5px; /* Add margin for spacing between input and button */
    }

    h1 {
      color: orange;
    }
  </style>
</head>
<body>

  <div>
    <form>
      <input type="search" placeholder="Search" aria-label="Search">
      <button type="submit">Search</button>
    </form>
    <h1>Welcome to Kebanda</h1>
  </div>

</body>
</html>

kebandaweb/kebanda/templates/kebanda/vendor_registration.html
{% extends 'kebanda/index.html' %}
{% load static %}
{% block title %}Vendor-registration{% endblock %}
{% block content %}

<h1 style="color: orange;">Register as a Vendor</h1>
<!-- vendor_registration.html -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 style="color: orange;">Enter your vendors info
        ...</h3>
    <!-- Vendor Registration Form Fields -->
    {{ vendor_form.as_p }}

    <h3 style="color: orange;">Fill in your Shops details here...</h3>
    <!-- Shop Creation Form Fields -->
    {{ shop_form.as_p }}
    <h3 style="color: orange;">confim it is you...</h3>
    <!-- Authentication Form Fields -->
    {{ auth_form.as_p }}

    <button type="submit">Register as Vendor</button>
</form>

{% endblock %}